using Content.Shared.GameCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ServerTab : Control
{
    public ServerTab()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Control.AddServerOptionSlider(GameConfigVars.SubGridSize, DivisionsSlider, 0, 3);
        Control.AddServerOptionSlider(GameConfigVars.SubGridUpdateFrequency, UpdateFrequencySlider, 1, 10);
        Control.AddServerOptionSlider(GameConfigVars.SubGridNetFrequency, NetFrequencySlider, 1, 30);
        Control.AddServerOptionFloatSlider(GameConfigVars.SubGridHeight, HeightSlider, 0.1f, 10f, 1f);

        Control.AddServerOptionCheckBox(GameConfigVars.AtmosDiffusionEnabled, AtmosDiffusionCheckBox);
        Control.AddServerOptionCheckBox(GameConfigVars.AtmosMovementEnabled, AtmosMovementCheckBox);
        Control.AddServerOptionCheckBox(GameConfigVars.AtmosHeatConductionEnabled, AtmosHeatConductionCheckBox);
        Control.AddServerOptionFloatSlider(GameConfigVars.AtmosTransferCoefficient, AtmosTransferCoefficientSlider, 0.1f, 10f, 1f);
        Control.AddServerOptionSlider(GameConfigVars.AtmosSteps, AtmosStepsSlider, 1, 20);
        Control.AddServerOptionFloatSlider(GameConfigVars.AtmosSpeedup, AtmosSpeedupSlider, 0.1f, 10f, 1f);

        Control.AddServerOptionCheckBox(GameConfigVars.HeatEnabled, HeatConductionCheckBox);
        Control.AddServerOptionSlider(GameConfigVars.HeatSteps, HeatStepsSlider, 1, 20);
        Control.AddServerOptionFloatSlider(GameConfigVars.HeatSpeedup, HeatSpeedupSlider, 0.1f, 100f, 1f);

        Control.Initialize();
    }
}
