using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Screens;

[GenerateTypedNameReferences]
public sealed partial class DefaultGameScreen : InGameScreen
{
    public DefaultGameScreen()
    {
        RobustXamlLoader.Load(this);

        AutoscaleMaxResolution = new Vector2i(1080, 770);

        SetAnchorPreset(ScreenContainer, LayoutPreset.Wide);
        SetAnchorPreset(ViewportContainer, LayoutPreset.Wide);
        SetAnchorPreset(MainViewport, LayoutPreset.Wide);

        Tabs.TabContainer.SetTabTitle(0, Loc.GetString("ui-viewport-header-statistics"));
        Tabs.TabContainer.SetTabTitle(1, Loc.GetString("ui-viewport-header-visuals"));
        Tabs.TabContainer.SetTabTitle(2, Loc.GetString("ui-viewport-header-simulation-options"));
    }
}
