using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultWindow
    {
        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            
            Tabs.SetTabTitle(0, Loc.GetString("ui-options-tab-graphics"));
            Tabs.SetTabTitle(1, Loc.GetString("ui-options-tab-controls"));

            UpdateTabs();
        }

        public void UpdateTabs()
        {
            GraphicsTab.Control.ReloadValues();
        }
    }
}
