using System.Linq;
using Content.Shared.Maps;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Tabs;

[GenerateTypedNameReferences]
public sealed partial class SimulationOptionsTab : Control
{
    [Dependency] private readonly IPrototypeManager _protoMan = default!;

    public string? SelectedMap;

    public event Action? OnMapSelected;
    public event Action? OnRestart;

    public SimulationOptionsTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Maps.OnItemSelected += args =>
        {
            SelectedMap = (string?) Maps[args.ItemIndex].Metadata;
        };

        Maps.OnItemDeselected += _ =>
        {
            SelectedMap = null;
        };

        SelectMapButton.OnPressed += _ => OnMapSelected?.Invoke();
        RestartButton.OnPressed += _ => OnRestart?.Invoke();
    }

    public void UpdateMapsList()
    {
        var maps = _protoMan.EnumeratePrototypes<SimulationMapPrototype>().ToList();
        maps.Sort((x, y) =>
            string.Compare(Loc.GetString(x.Name), Loc.GetString(y.Name), StringComparison.Ordinal));
        Maps.Clear();
        foreach (var mapProto in maps)
        {
            Maps.Add(GetItem(mapProto.ID, Loc.GetString(mapProto.Name), Loc.GetString(mapProto.Description), Maps));
        }
    }

    private static ItemList.Item GetItem(string id, string name, string desc, ItemList itemList)
    {
        return new ItemList.Item(itemList)
        {
            Text = name,
            Metadata = id,
            TooltipText = desc,
        };
    }
}
