using Content.Shared.Atmospherics.Factory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Tabs;

[GenerateTypedNameReferences]
public sealed partial class SubgridEditorTab : Control
{
    [Dependency] private readonly GasMixtureFactory _gasFactory = default!;

    public const float HeatEnergyUnit = 100000f; // Mega Joules

    public event Action<float>? OnGasValueChanged;
    public event Action<float>? OnHeatValueChanged;
    public event Action<int>? OnGasSelected;

    public SubgridEditorTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GasOptions.OnItemSelected += val =>
        {
            GasOptions.SelectId(val.Id);
            OnGasSelected?.Invoke(val.Id);
        };

        var gasSpinBox = new FloatSpinBox(0.1f, 1);
        AddGasBox.AddChild(gasSpinBox);
        gasSpinBox.OnValueChanged += val => OnGasValueChanged?.Invoke(val.Value);

        var gasMeasureLabel = new Label { Text = Loc.GetString("unit-moles") };
        AddGasBox.AddChild(gasMeasureLabel);

        var heatSpinBox = new FloatSpinBox(0.1f, 1);
        AddHeatBox.AddChild(heatSpinBox);
        heatSpinBox.OnValueChanged += val => OnHeatValueChanged?.Invoke(val.Value * HeatEnergyUnit);

        var heatMeasureLabel = new Label { Text = Loc.GetString("unit-mega-joules") };
        AddHeatBox.AddChild(heatMeasureLabel);
    }

    public void UpdateGasOptions()
    {
        GasOptions.Clear();
        GasOptions.AddItem(Loc.GetString("editor-gas-selected-none"), -1);
        for (int i = 0; i < _gasFactory.Count; i++)
        {
            var gasProto = _gasFactory[i];
            GasOptions.AddItem(Loc.GetString(gasProto.Name), gasProto.GasId);
        }
    }
}
