using System.Linq;
using Content.Client.Atmospherics;
using Content.Shared.Atmospherics.Factory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Tabs;

[GenerateTypedNameReferences]
public sealed partial class SubgridEditorTab : Control
{
    [Dependency] private readonly GasMixtureFactory _gasFactory = default!;

    public event Action<int>? OnModeSelected;
    public event Action<float>? OnValueChanged;
    public event Action<byte>? OnGasSelected;

    public SubgridEditorTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EditorModes.OnItemSelected += val =>
        {
            EditorModes.SelectId(val.Id);
            OnModeSelected?.Invoke(val.Id);
        };

        GasOptions.OnItemSelected += val =>
        {
            GasOptions.SelectId(val.Id);
            OnGasSelected?.Invoke((byte) val.Id);
        };

        var spinBox = new FloatSpinBox(0.1f, 1);
        Editor.AddChild(spinBox);
        spinBox.OnValueChanged += val => OnValueChanged?.Invoke(val.Value);

        UpdateEditorModes();
    }

    public void UpdateEditorModes()
    {
        EditorModes.Clear();
        var modes = Enum.GetValuesAsUnderlyingType<SubGridPlacementMode>().Cast<SubGridPlacementMode>().ToList();
        foreach (var mode in modes)
        {
            EditorModes.AddItem(Loc.GetString($"subgrid-editor-mode-{mode.ToString()}"), (int) mode);
        }

    }

    public void UpdateGasOptions()
    {
        GasOptions.Clear();
        for (int i = 0; i < _gasFactory.Count; i++)
        {
            var gasProto = _gasFactory[i];
            GasOptions.AddItem(Loc.GetString(gasProto.Name), gasProto.GasId);
        }
    }

    public void SetGasOptionVisible(bool visible)
    {
        GasOptions.Visible = visible;
    }
}
