using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Tabs;

[GenerateTypedNameReferences]
public sealed partial class VisualsTab : Control
{
    public VisualsTab()
    {
        RobustXamlLoader.Load(this);
    }
}
