using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Tabs.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GameTabContainer : UIWidget
{
    public GameTabContainer()
    {
        RobustXamlLoader.Load(this);
    }
}
