using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmospherics;
using Content.Shared.Constants;
using Content.Shared.Temperature;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

// TODO rework this to be prettier, right now it's just a copy-paste from SS14
[GenerateTypedNameReferences]
public sealed partial class GasInspectControl : BoxContainer
{
    public GasInspectControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(GasMixEntry? mix)
    {
        if (mix == null)
        {
            CTopBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-no-data")
            });
            MinSize = new Vector2(CTopBox.DesiredSize.X + 40, MinSize.Y);
            return;
        }

        CEnvironmentMix.RemoveAllChildren();
        GenerateGasDisplay(mix.Value, CEnvironmentMix);

        MinSize = new Vector2(CEnvironmentMix.DesiredSize.X + 40, MinSize.Y);
    }

    private void GenerateGasDisplay(GasMixEntry gasMix, Control parent)
    {
        var panel = new PanelContainer
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            Margin = new Thickness(4),
            PanelOverride = new StyleBoxFlat
                { BorderColor = Color.FromHex("#4f4f4f"), BorderThickness = new Thickness(1) }
        };
        var dataContainer = new BoxContainer
            { Orientation = LayoutOrientation.Vertical, VerticalExpand = true, Margin = new Thickness(4) };


        parent.AddChild(panel);
        panel.AddChild(dataContainer);

        // Volume label
        var volBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

        volBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-volume-text")
        });
        volBox.AddChild(new Control
        {
            MinSize = new Vector2(10, 0),
            HorizontalExpand = true
        });
        volBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-volume-val-text", ("volume", $"{gasMix.Volume:0.##}")),
            Align = Label.AlignMode.Right,
            HorizontalExpand = true
        });
        dataContainer.AddChild(volBox);

        // Pressure label
        var presBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

        presBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-pressure-text")
        });
        presBox.AddChild(new Control
        {
            MinSize = new Vector2(10, 0),
            HorizontalExpand = true
        });
        presBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-pressure-val-text", ("pressure", $"{gasMix.Pressure:0.00}")),
            Align = Label.AlignMode.Right,
            HorizontalExpand = true
        });
        dataContainer.AddChild(presBox);

        // If there is no gas, it doesn't really have a temperature, so skip displaying it
        if (gasMix.Pressure > SystemConstants.GasMinMoles)
        {
            // Temperature label
            var tempBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

            tempBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-temperature-text")
            });
            tempBox.AddChild(new Control
            {
                MinSize = new Vector2(10, 0),
                HorizontalExpand = true
            });
            tempBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-temperature-val-text",
                    ("tempK", $"{gasMix.Temperature:0.0}"),
                    ("tempC", $"{TemperatureHelpers.KelvinToCelsius(gasMix.Temperature):0.0}")),
                Align = Label.AlignMode.Right,
                HorizontalExpand = true
            });
            dataContainer.AddChild(tempBox);
        }

        if (gasMix.Gases == null || gasMix.Gases?.Length == 0)
        {
            // Separator
            dataContainer.AddChild(new Control
            {
                MinSize = new Vector2(0, 10)
            });

            // Add a label that there are no gases so it's less confusing
            dataContainer.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-no-gas-text"),
                FontColorOverride = Color.Gray
            });
            // return, everything below is for the fancy gas display stuff
            return;
        }

        // Separator
        dataContainer.AddChild(new Control
        {
            MinSize = new Vector2(0, 10)
        });

        // Add a table with all the gases
        var tableKey = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical
        };
        var tableVal = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical
        };
        var tablePercent = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical
        };
        dataContainer.AddChild(new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                tableKey,
                new Control
                {
                    MinSize = new Vector2(10, 0),
                    HorizontalExpand = true
                },
                tableVal,
                new Control
                {
                    MinSize = new Vector2(10, 0),
                    HorizontalExpand = true
                },
                tablePercent
            }
        });
        // This is the gas bar thingy
        var height = 30;
        var gasBar = new SplitBar
        {
            MinHeight = height,
            MinBarSize = new Vector2(12, 0)
        };
        // Separator
        dataContainer.AddChild(new Control
        {
            MinSize = new Vector2(0, 10),
            VerticalExpand = true
        });

        var totalGasAmount = 0f;
        foreach (var gas in gasMix.Gases!)
        {
            totalGasAmount += gas.Amount;
        }

        tableKey.AddChild(new Label
            { Text = Loc.GetString("gas-analyzer-window-gas-column-name"), Align = Label.AlignMode.Center });
        tableVal.AddChild(new Label
            { Text = Loc.GetString("gas-analyzer-window-molarity-column-name"), Align = Label.AlignMode.Center });
        tablePercent.AddChild(new Label
            { Text = Loc.GetString("gas-analyzer-window-percentage-column-name"), Align = Label.AlignMode.Center });

        tableKey.AddChild(new StripeBack());
        tableVal.AddChild(new StripeBack());
        tablePercent.AddChild(new StripeBack());

        for (var j = 0; j < gasMix.Gases.Length; j++)
        {
            var gas = gasMix.Gases[j];
            var color = Color.FromHex($"#{gas.Color}", Color.White);
            // Add to the table
            tableKey.AddChild(new Label
            {
                Text = Loc.GetString(gas.Name)
            });
            tableVal.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-molarity-text",
                    ("mol", $"{gas.Amount:0.00}")),
                Align = Label.AlignMode.Right,
            });
            tablePercent.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-percentage-text",
                    ("percentage", $"{(gas.Amount / totalGasAmount * 100):0.0}")),
                Align = Label.AlignMode.Right
            });

            // Add to the gas bar //TODO: highlight the currently hover one
            gasBar.AddEntry(gas.Amount,
                color,
                tooltip: Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                    ("gasName", gas.Name),
                    ("amount", $"{gas.Amount:0.##}"),
                    ("percentage", $"{(gas.Amount / totalGasAmount * 100):0.#}")));
        }

        dataContainer.AddChild(gasBar);
    }
}
