using System.Numerics;
using Content.Shared.Atmospherics;
using Content.Shared.Constants;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

// TODO rework this to be prettier, right now it's just a copy-paste from SS14
[GenerateTypedNameReferences]
public sealed partial class GasInspectControl : BoxContainer
{
    public GasInspectControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(GasMixEntry mix)
    {
        CEnvironmentMix.RemoveAllChildren();
        GenerateGasDisplay(mix);
    }

    private void GenerateGasDisplay(GasMixEntry gasMix)
    {
        // Volume label
        var volBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

        volBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-volume-text")
        });
        volBox.AddChild(new Control
        {
            MinSize = new Vector2(10, 0),
            HorizontalExpand = true
        });
        volBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-volume-val-text", ("volume", $"{gasMix.Volume:0.####}")),
            Align = Label.AlignMode.Right,
            HorizontalExpand = true
        });
        CEnvironmentMix.AddChild(volBox);

        // Pressure label
        var presBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

        presBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-pressure-text")
        });
        presBox.AddChild(new Control
        {
            MinSize = new Vector2(10, 0),
            HorizontalExpand = true
        });
        presBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-pressure-val-text", ("pressure", $"{gasMix.Pressure:0.00}")),
            Align = Label.AlignMode.Right,
            HorizontalExpand = true
        });
        CEnvironmentMix.AddChild(presBox);

        // Temperature label
        var tempBox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

        tempBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-temperature-text")
        });
        tempBox.AddChild(new Control
        {
            MinSize = new Vector2(10, 0),
            HorizontalExpand = true
        });
        tempBox.AddChild(new Label
        {
            Text = Loc.GetString("gas-analyzer-window-temperature-val-text", ("temperature", $"{gasMix.Temperature:0.00}")),
            Align = Label.AlignMode.Right,
            HorizontalExpand = true
        });
        CEnvironmentMix.AddChild(tempBox);

        if (gasMix.Gases == null || gasMix.Gases?.Length == 0)
        {
            // Separator
            CEnvironmentMix.AddChild(new Control
            {
                MinSize = new Vector2(0, 10)
            });

            // Add a label that there are no gases so it's less confusing
            CEnvironmentMix.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-no-gas-text"),
                FontColorOverride = Color.Gray
            });
            // return, everything below is for the fancy gas display stuff
            return;
        }

        // Separator
        CEnvironmentMix.AddChild(new Control
        {
            MinSize = new Vector2(0, 10)
        });

        // Add a table with all the gases
        var tableKey = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical
        };
        var tableVal = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical
        };
        var tablePercent = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical
        };
        CEnvironmentMix.AddChild(new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                tableKey,
                new Control
                {
                    MinSize = new Vector2(10, 0),
                    HorizontalExpand = true,
                },
                tableVal,
                new Control
                {
                    MinSize = new Vector2(10, 0),
                    HorizontalExpand = true,
                },
                tablePercent
            }
        });
        // This is the gas bar thingy
        var height = 30;
        var gasBar = new SplitBar
        {
            MinHeight = height,
            MinBarSize = new Vector2(12, 1)
        };
        // Separator
        CEnvironmentMix.AddChild(new Control
        {
            MinSize = new Vector2(0, 10),
            VerticalExpand = true
        });

        var totalGasAmount = 0f;
        foreach (var gas in gasMix.Gases!)
        {
            totalGasAmount += gas.Amount;
        }

        if (totalGasAmount < SystemConstants.GasMinMoles)
        {
            // There is no gas
            GasPlaceholder.Visible = true;
            return;
        }

        tableKey.AddChild(new Label
            { Text = Loc.GetString("gas-analyzer-window-gas-column-name"), Align = Label.AlignMode.Center });
        tableVal.AddChild(new Label
            { Text = Loc.GetString("gas-analyzer-window-molarity-column-name"), Align = Label.AlignMode.Center });
        tablePercent.AddChild(new Label
            { Text = Loc.GetString("gas-analyzer-window-percentage-column-name"), Align = Label.AlignMode.Center });

        tableKey.AddChild(new StripeBack());
        tableVal.AddChild(new StripeBack());
        tablePercent.AddChild(new StripeBack());

        for (var j = 0; j < gasMix.Gases.Length; j++)
        {
            var gas = gasMix.Gases[j];
            if (gas.Amount < SystemConstants.GasMinMoles)
                continue;

            // Add to the table
            tableKey.AddChild(new Label
            {
                Text = Loc.GetString(gas.Name)
            });
            tableVal.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-molarity-text",
                    ("mol", $"{gas.Amount:0.00}")),
                Align = Label.AlignMode.Right,
            });
            tablePercent.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-percentage-text",
                    ("percentage", $"{(gas.Amount / totalGasAmount * 100f):0.0}")),
                Align = Label.AlignMode.Right
            });

            // Add to the gas bar //TODO: highlight the currently hover one
            gasBar.AddEntry(MathF.Max(gas.Amount / totalGasAmount * 100f, 1f),
                gas.Color,
                tooltip: Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                    ("gasName", Loc.GetString(gas.Name)),
                    ("amount", $"{gas.Amount:0.####}"),
                    ("percentage", $"{(gas.Amount / totalGasAmount * 100f):0.#}")));
        }

        CEnvironmentMix.AddChild(gasBar);
    }
}
