using Content.Shared.Temperature;
using Content.Shared.Temperature.HeatContainers;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

/// <summary>
/// A control that can inspect <see cref="HeatContainer"/>s
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HeatInspectControl : BoxContainer
{
    public HeatInspectControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate<T>(T container) where T : IHeatContainer
    {
        DataContainer.RemoveAllChildren();
        // Temperature
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-temperature",
                ("kelvin", $"{container.Temperature:0.0}"),
                ("celsius", $"{container.TemperatureC:0.0}"))
        });
        // Heat Capacity
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-heat-capacity",
                ("capacity", $"{container.HeatCapacity:0.0}"))
        });
        // Internal Energy
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-internal-energy",
                ("energy", $"{container.InternalEnergy:0.0}"))
        });

        if (container is ConductiveHeatContainer conductive)
        {
            // Conductance
            DataContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("heat-container-inspect-conductance",
                    ("conductance", $"{conductive.ThermalConductance:0.0}"))
            });
        }
    }

    public void Populate(ConductiveHeatContainer container)
    {
        DataContainer.RemoveAllChildren();
        // Temperature
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-temperature",
                ("kelvin", $"{container.Temperature:0.0}"),
                ("celsius", $"{container.TemperatureC:0.0}"))
        });
        // Heat Capacity
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-heat-capacity",
                ("capacity", $"{container.HeatCapacity:0.0}"))
        });
        // Internal Energy
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-internal-energy",
                ("energy", $"{container.InternalEnergy:0.0}"))
        });

            // Conductance
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-conductance",
                ("conductance", $"{container.ThermalConductance:0.0}"))
        });
    }

    public void Populate(float temperature, float heatCapacity, float thermalConductance)
    {
        DataContainer.RemoveAllChildren();
        // Temperature
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-temperature",
                ("kelvin", $"{temperature:0.0}"),
                ("celsius", $"{TemperatureHelpers.KelvinToCelsius(temperature):0.0}"))
        });
        // Heat Capacity
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-heat-capacity",
                ("capacity", $"{heatCapacity:0.0}"))
        });
        // Conductance
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-conductance",
                ("conductance", $"{thermalConductance:0.0}"))
        });
        // Internal Energy
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-internal-energy",
                ("energy", $"{temperature * heatCapacity:0.0}"))
        });
    }
}
