using Content.Shared.Temperature.HeatContainers;
using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

/// <summary>
/// A control that can inspect <see cref="HeatContainer"/>s
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HeatInspectControl : BoxContainer
{
    public HeatInspectControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(HeatContainer container)
    {
        DataContainer.RemoveAllChildren();
        // Temperature
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-temperature",
                ("kelvin", $"{container.Temperature:0.0}"),
                ("celsius", $"{container.TemperatureC:0.0}"))
        });
        // Heat Capacity
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-heat-capacity",
                ("capacity", $"{container.HeatCapacity:0.0}"))
        });
        // Conductance
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-conductance",
                ("conductance", $"{container.ThermalConductance:0.0}"))
        });
        // Internal Energy
        DataContainer.AddChild(new RichTextLabel
        {
            Text = Loc.GetString("heat-container-inspect-internal-energy",
                ("energy", $"{container.InternalEnergy:0.0}"))
        });
    }
}
